apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels: # these are deployment labels
    app: frontend
    tier: web
    project: expense
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
  # these are used to select the pod to create it's replicas
    matchLabels: 
      tier: web
      app: frontend
      project: expense
  # this is pod replicas' definition which are going to be generated
  template:
    metadata:
    # these labels belongs to replicas which are going to be generated
      labels:
        tier: web
        app: frontend
        project: expense
    spec:
      containers:
      - name: frontend
        image: avkdocr/frontend:v2
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    tier: web
    app: frontend
    project: expense 
  ports:
  - name: frontend-lb-port
    protocol: TCP
    port: 80 # this port number is belongs to this service
    targetPort: 80 # this is target containr's port
