apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels: # these are deployment labels
    app: mysql
    tier: db
    project: expense
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
  # these are used to select the pod to create it's replicas
    matchLabels: 
      tier: db
      app: mysql
      project: expense
  # this is pod replicas' definition which are going to be generated
  template:
    metadata:
    # these labels belongs to replicas which are going to be generated
      labels:
        tier: db
        app: mysql
        project: expense
    spec:
      containers:
      - name: mysql
        image: avkdocr/mysql:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-cip
  namespace: expense
spec:
  selector:
    tier: db
    app: mysql
    project: expense 
  ports:
  - name: mysql-cip-port
    protocol: TCP
    port: 3306 # this port number is belongs to this service
    targetPort: 3306 # this is target containr's port
